apiVersion: v1
kind: ServiceAccount
metadata:
  name: methodingress-controller
  namespace: methodingress-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: methodingress-controller
rules:
- apiGroups: ["networking.microendpoints.ovena.io"]
  resources: ["methodingresses", "methodingresses/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: methodingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: methodingress-controller
subjects:
- kind: ServiceAccount
  name: methodingress-controller
  namespace: methodingress-system
